name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.REGISTRY_PASS }}" | docker login -u "${{ secrets.REGISTRY_USER }}" --password-stdin

    - name: Extract version from tag
      id: extract_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        docker build -t sresteves/erpbusiness:${{ env.VERSION }} -t sresteves/erpbusiness:latest .
        docker push sresteves/erpbusiness:${{ env.VERSION }}
        docker push sresteves/erpbusiness:latest