name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.REGISTRY_PASS }}" | docker login -u "${{ secrets.REGISTRY_USER }}" --password-stdin

    - name: Set version
      id: set_version
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        else
          echo "VERSION=latest" >> $GITHUB_ENV
        fi

    - name: Build Docker image
      run: |
        docker build -t sresteves/erpbusiness:${{ env.VERSION }} -t sresteves/erpbusiness:latest .

    - name: Scan Docker image for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: sresteves/erpbusiness:${{ env.VERSION }}

    - name: Push Docker image
      run: |
        docker push sresteves/erpbusiness:${{ env.VERSION }}
        docker push sresteves/erpbusiness:latest
